- Read sheet "Australia by Residence" from Australia.xlsx
- Ignore the first 20 rows.
- List all Column and Row indexes(Print their names)

Dataset Analysis
- Describe the dataset
- Use values and index attributes on both Row and Column Indexes
- Check Shape, Datatypes and other attributes and observe the datatype of each columns' data
  

Drop
- Delete all Data where the Type = "Emigrants" or Type is not "Immigrants" (Row Deletion)
- Find columns for which more than 50% data is missing and drop them (Column Deletion)
- Drop Unnessary Columns: Type, Coverage, Area, Reg, Dev (Column deletion)
    Your columns should now look like "OdName,AreaName,RegName,DevName,1980 ... 2008"

Rename
- Rename columns :OdName -> Country; RegName -> Region
- Convert Column Names with Int type to Strings to avoid index errors with string indexing "1980, 1981 etc." => " '1980', '1981' ... " (Use rename)
- Find Total number of immigrants for all years, and create a new column Total in data Frame

Head Tail Sort
- Sort Data by the new column Total in descending order and analyze the fist few rows. (get first few rows using head)
    - find something weird in the dataset ? Delete that row 'world'
- Analyze last few rows also in the sorted result (Don't sort inplace)

- Check if these have all unique values or not:
    - countries
    - continents (AreaName)
    - country continent pairs


- Find countries for which no of immigrants for all years is 0
- Find count of above countries
- Find countries for which no of immigrants is 0 for any year

Save Data
- Drop the row where AreaName is 'World'
- Save the dataset to a new file AustraliaFiltered.xlsx

# --------------------------------------------------------------------------------------------------------------

- Read sheet "Australia by Residence" from Australia.xlsx
- Ignore the first 20 rows.
- List all Column and Row indexes(Print their names)

In [1]:
import os 
import pandas as pd
import numpy as np

In [2]:
os.chdir(r"C:\Users\Samarpit\Desktop\LEARBAY\weekday2019_09_05\Assignments")
aus_raw = pd.read_excel("Australia.xlsx",sheet_name='Australia by Residence',skiprows=20)
aus_raw.head(3)

,Type,Coverage,OdName,AREA,AreaName,REG,RegName,DEV,DevName,1980,...,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013
0,Emigrants,Both,Afghanistan,935,Asia,5501,Southern Asia,902,Developing regions,0,...,80,120,70,80,120,..,..,..,..,..
1,Emigrants,Both,Albania,908,Europe,925,Southern Europe,901,Developed regions,0,...,30,40,30,30,30,..,..,..,..,..
2,Emigrants,Both,Algeria,903,Africa,912,Northern Africa,902,Developing regions,20,...,20,20,30,40,50,..,..,..,..,..

# Dataset Analysis
- Describe the dataset

In [3]:
aus_raw.describe(include='all')

,Type,Coverage,OdName,AREA,AreaName,REG,RegName,DEV,DevName,1980,...,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013
count,448,448,448,448.000000,448,448.000000,448,448.000000,448,448.000000,...,448.000000,448.000000,448.000000,448.000000,448.000000,448,448,448,448,448
unique,2,1,224,NaN,7,NaN,23,NaN,3,NaN,...,NaN,NaN,NaN,NaN,NaN,1,1,1,1,1
top,Emigrants,Both,Netherlands,NaN,Africa,NaN,Caribbean,NaN,Developing regions,NaN,...,NaN,NaN,NaN,NaN,NaN,..,..,..,..,..
freq,224,448,2,NaN,112,NaN,46,NaN,344,NaN,...,NaN,NaN,NaN,NaN,NaN,448,448,448,448,448
mean,NaN,NaN,NaN,912.955357,NaN,1208.040179,NaN,902.642857,NaN,1228.348214,...,2514.241071,2545.357143,2709.866071,3023.348214,3376.116071,NaN,NaN,NaN,NaN,NaN
std,NaN,NaN,NaN,15.019682,NaN,1109.669573,NaN,9.165500,NaN,10145.734028,...,19834.528214,20203.441660,21786.641444,24542.748186,27950.462893,NaN,NaN,NaN,NaN,NaN
min,NaN,NaN,NaN,903.000000,NaN,905.000000,NaN,901.000000,NaN,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,NaN,NaN,NaN,NaN
25%,NaN,NaN,NaN,903.750000,NaN,914.000000,NaN,902.000000,NaN,0.000000,...,10.000000,10.000000,10.000000,10.000000,10.000000,NaN,NaN,NaN,NaN,NaN
50%,NaN,NaN,NaN,908.000000,NaN,922.000000,NaN,902.000000,NaN,10.000000,...,50.000000,50.000000,60.000000,70.000000,75.000000,NaN,NaN,NaN,NaN,NaN
75%,NaN,NaN,NaN,909.000000,NaN,926.000000,NaN,902.000000,NaN,130.000000,...,400.000000,410.000000,455.000000,480.000000,512.500000,NaN,NaN,NaN,NaN,NaN
max,NaN,NaN,NaN,999.000000,NaN,5501.000000,NaN,999.000000,NaN,184290.000000,...,350990.000000,363470.000000,402210.000000,460650.000000,535970.000000,NaN,NaN,NaN,NaN,NaN

- Use values and index attributes on both Row and Column Indexes

In [4]:
# doubt

- Check Shape, Datatypes and other attributes and observe the datatype of each columns' data

In [5]:
aus_raw.shape

(448, 43)

# Drop
- Delete all Data where the Type = "Emigrants" or Type is not "Immigrants" (Row Deletion)

In [6]:
filter1 = aus_raw["Type"]=="Immigrants"
filter1.head()
aus_fil=aus_raw[filter1]
aus_fil.tail()

,Type,Coverage,OdName,AREA,AreaName,REG,RegName,DEV,DevName,1980,...,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013
443,Immigrants,Both,Yemen,935,Asia,922,Western Asia,902,Developing regions,10,...,40,20,10,40,40,..,..,..,..,..
444,Immigrants,Both,Zambia,903,Africa,910,Eastern Africa,902,Developing regions,150,...,370,240,410,410,400,..,..,..,..,..
445,Immigrants,Both,Zimbabwe,903,Africa,910,Eastern Africa,902,Developing regions,630,...,1790,1560,1880,2180,2270,..,..,..,..,..
446,Immigrants,Both,Unknown,999,World,999,World,999,World,4060,...,1650,1800,2320,18310,4970,..,..,..,..,..
447,Immigrants,Both,Total,999,World,999,World,999,World,184290,...,350990,363470,402210,460650,535970,..,..,..,..,..

- Find columns for which more than 50% data is missing and drop them (Column Deletion)

In [7]:
(aus_fil.isna().sum()/aus_fil.shape[0])*100

Type        0.0
Coverage    0.0
OdName      0.0
AREA        0.0
AreaName    0.0
REG         0.0
RegName     0.0
DEV         0.0
DevName     0.0
1980        0.0
1981        0.0
1982        0.0
1983        0.0
1984        0.0
1985        0.0
1986        0.0
1987        0.0
1988        0.0
1989        0.0
1990        0.0
1991        0.0
1992        0.0
1993        0.0
1994        0.0
1995        0.0
1996        0.0
1997        0.0
1998        0.0
1999        0.0
2000        0.0
2001        0.0
2002        0.0
2003        0.0
2004        0.0
2005        0.0
2006        0.0
2007        0.0
2008        0.0
2009        0.0
2010        0.0
2011        0.0
2012        0.0
2013        0.0
dtype: float64

- Drop Unnessary Columns: Type, Coverage, Area, Reg, Dev (Column deletion) Your columns should now look like "OdName,AreaName,RegName,DevName,1980 ... 2008"

In [8]:
aus_del=aus_fil.drop(['Type','Coverage','AREA','REG','DEV',2009,2010,2011,2012,2013],axis=1)

# Rename
- Rename columns :OdName -> Country; RegName -> Region

In [9]:
aus_del = aus_del.rename(columns ={'OdName':'Country','RegName':'Region'})
aus_del.columns

Index([ 'Country', 'AreaName',   'Region',  'DevName',       1980,       1981,
             1982,       1983,       1984,       1985,       1986,       1987,
             1988,       1989,       1990,       1991,       1992,       1993,
             1994,       1995,       1996,       1997,       1998,       1999,
             2000,       2001,       2002,       2003,       2004,       2005,
             2006,       2007,       2008],
      dtype='object')

- Convert Column Names with Int type to Strings to avoid index errors with string indexing "1980, 1981 etc." => " '1980', '1981' ... " (Use rename)

In [10]:
a={}
for i in range(1980,2009):
    a[i]=a.get(i,str(i))

aus_del = aus_del.rename(columns = a)
aus_del.columns

Index(['Country', 'AreaName', 'Region', 'DevName', '1980', '1981', '1982',
       '1983', '1984', '1985', '1986', '1987', '1988', '1989', '1990', '1991',
       '1992', '1993', '1994', '1995', '1996', '1997', '1998', '1999', '2000',
       '2001', '2002', '2003', '2004', '2005', '2006', '2007', '2008'],
      dtype='object')

- Find Total number of immigrants for all years, and create a new column Total in data Frame

In [11]:
aus_del.dtypes
aus_del['Total']=aus_del.iloc[:,5:29].sum(axis=1) #why this is not working?? Reminder:- CHeck other solution

#Testing
aus_del['Total']=aus_del['1980']+aus_del['1981']+aus_del['1982']+aus_del['1983']\
+aus_del['1984']+aus_del['1985']+aus_del['1986']+aus_del['1987']+aus_del['1988']\
+aus_del['1989']+aus_del['1990']+aus_del['1991']+aus_del['1992']+aus_del['1993']\
+aus_del['1994']+aus_del['1995']+aus_del['1996']+aus_del['1997']+aus_del['1998']\
+aus_del['1999']+aus_del['2000']+aus_del['2001']+aus_del['2002']+aus_del['2003']\
+aus_del['2004']+aus_del['2005']+aus_del['2006']+aus_del['2007']+aus_del['2008']


aus_del.tail()
# aus_del.iloc[443,]
aus_del[aus_del.Country=='Yemen']
# aus_del[aus_del.Country=='Yemen']['Total']

,Country,AreaName,Region,DevName,1980,1981,1982,1983,1984,1985,...,2000,2001,2002,2003,2004,2005,2006,2007,2008,Total
443,Yemen,Asia,Western Asia,Developing regions,10,0,0,10,20,10,...,20,60,40,150,40,20,10,40,40,570

# Head Tail Sort
- Sort Data by the new column Total in descending order and analyze the fist few rows. (get first few rows using head)
 - find something weird in the dataset ? Delete that row 'world'

In [12]:
aus_del.sort_values('Total',ascending=False).head()
aus_sorted=aus_del[aus_del['AreaName']!='World']

- Analyze last few rows also in the sorted result (Don't sort inplace)

In [13]:
aus_sorted.sort_values('Total',ascending=False).head()
# Anguilla
aus_sorted.sort_values('Total',ascending=True)

,Country,AreaName,Region,DevName,1980,1981,1982,1983,1984,1985,...,2000,2001,2002,2003,2004,2005,2006,2007,2008,Total
308,Guadeloupe,Latin America and the Caribbean,Caribbean,Developing regions,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
427,Turks and Caicos Islands,Latin America and the Caribbean,Caribbean,Developing regions,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
395,Saint Vincent and the Grenadines,Latin America and the Caribbean,Caribbean,Developing regions,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
306,Greenland,Northern America,Northern America,Developed regions,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
435,United States Virgin Islands,Latin America and the Caribbean,Caribbean,Developing regions,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
442,Western Sahara,Africa,Northern Africa,Developing regions,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
393,Saint Kitts and Nevis,Latin America and the Caribbean,Caribbean,Developing regions,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
315,Holy See,Europe,Southern Europe,Developed regions,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
230,Anguilla,Latin America and the Caribbean,Caribbean,Developing regions,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
353,Mayotte,Africa,Eastern Africa,Developing regions,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
262,Central African Republic,Africa,Middle Africa,Developing regions,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
270,Comoros,Africa,Eastern Africa,Developing regions,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
392,Saint Helena,Africa,Western Africa,Developing regions,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
350,Martinique,Latin America and the Caribbean,Caribbean,Developing regions,0,0,0,0,0,0,...,0,0,0,0,0,0,10,0,0,10
292,Faeroe Islands,Europe,Northern Europe,Developed regions,0,0,0,0,0,0,...,0,0,0,0,0,0,10,0,0,10
426,Turkmenistan,Asia,Central Asia,Developing regions,0,0,0,0,0,0,...,0,10,0,0,0,0,0,0,0,10
340,Liechtenstein,Europe,Western Europe,Developed regions,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,10,10
257,Cabo Verde,Africa,Western Africa,Developing regions,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,10
297,French Guiana,Latin America and the Caribbean,South America,Developing regions,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,10
288,Equatorial Guinea,Africa,Middle Africa,Developing regions,0,0,0,0,0,10,...,0,0,0,0,0,0,0,0,0,10
441,Wallis and Futuna Islands,Oceania,Polynesia,Developing regions,0,0,0,0,0,0,...,0,0,0,0,10,0,0,0,0,10
358,Montserrat,Latin America and the Caribbean,Caribbean,Developing regions,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,10,10
234,Aruba,Latin America and the Caribbean,Caribbean,Developing regions,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,10
372,Northern Mariana Islands,Oceania,Micronesia,Developing regions,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,10,10
255,Burkina Faso,Africa,Western Africa,Developing regions,0,0,0,0,0,0,...,0,0,0,0,0,10,0,10,0,20
314,Haiti,Latin America and the Caribbean,Caribbean,Developing regions,0,0,0,0,10,10,...,0,0,0,0,0,0,0,0,0,20
312,Guinea-Bissau,Africa,Western Africa,Developing regions,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,20
279,Democratic People's Republic of Korea,Asia,Eastern Asia,Developing regions,0,0,0,0,0,0,...,0,0,0,10,0,0,0,0,0,20
394,Saint Lucia,Latin America and the Caribbean,Caribbean,Developing regions,0,0,0,0,0,0,...,0,0,10,0,0,0,0,0,10,20
227,American Samoa,Oceania,Polynesia,Developing regions,0,0,0,0,0,20,...,0,0,0,0,0,0,0,0,10,30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
286,Egypt,Africa,Northern Africa,Developing regions,330,400,390,400,650,800,...,1090,1380,1840,2890,4070,3800,2960,2000,1520,38710
375,Pakistan,Asia,Southern Asia,Developing regions,290,420,280,350,460,950,...,2050,1770,1860,2570,2540,3360,4580,7030,6450,52290
365,Netherlands,Europe,Western Europe,Developed regions,2700,3330,3460,1680,1210,1380,...,2360,2250,2080,2330,1900,1870,1980,1940,2030,53820
425,Turkey,Asia,Western Asia,Developing regions,1500,1390,870,930,1320,1690,...,1900,1890,2470,2490,1850,1720,1690,1860,2080,55890
296,France,Europe,Western Europe,Developed regions,1400,1730,1700,1650,1480,1590,...,2570,2770,2790,2750,2950,3210,3620,4330,4910,65430
325,Italy,Europe,Southern Europe,Developed regions,4210,4310,2620,2200,2400,2850,...,1750,1890,1690,1810,2250,2250,2560,2590,2840,67190
408,Sri Lanka,Asia,Southern Asia,Developing regions,410,510,580,740,2680,1640,...,2660,2870,3210,3050,2590,3410,4330,5620,6820,74710
294,Fiji,Oceania,Melanesia,Developing regions,1260,1700,1640,1440,1530,1830,...,2790,3040,2500,2710,2860,2890,4120,2820,3510,78000
336,Lebanon,Asia,Western Asia,Developing regions,1240,1350,1440,1410,3110,3000,...,2970,2770,2600,3000,2840,2710,3110,2500,10450,85660
305,Greece,Europe,Southern Europe,Developed regions,4280,5040,3560,3210,4060,4300,...,2170,2010,2300,1880,1300,1380,1260,1190,1130,87060
268,"China, Taiwan Province of China",Asia,Eastern Asia,Developing regions,220,270,310,270,390,520,...,5080,5240,5110,4810,3410,3290,3350,3580,4550,88700
378,Papua New Guinea,Oceania,Melanesia,Developing regions,5610,5820,5820,5080,4730,4390,...,1390,1530,1440,1340,1710,1630,2020,1930,2340,93730
323,Ireland,Europe,Northern Europe,Developed regions,950,1470,1500,1220,740,1500,...,5050,5500,5490,6040,4560,4410,4630,6130,8930,95870
440,Viet Nam,Asia,South-Eastern Asia,Developing regions,130,70,200,920,2860,2140,...,3430,3800,4410,4840,4500,5110,6610,8310,11210,119060
302,Germany,Europe,Western Europe,Developed regions,3300,4620,7140,5160,2800,2700,...,4650,5180,5170,5390,4870,4980,5240,6110,6710,121310
260,Canada,Northern America,Northern America,Developed regions,2920,3770,3830,3170,3030,3390,...,5710,6050,6240,6430,6350,6520,6700,7020,7930,140860
386,Republic of Korea,Asia,Eastern Asia,Developing regions,390,620,1030,870,880,1180,...,5630,7420,8650,9640,10210,11670,13950,15390,17240,156680
417,Thailand,Asia,South-Eastern Asia,Developing regions,4730,5300,4230,6790,3530,3100,...,5070,6970,7690,7900,7630,8370,9990,11750,13350,162860
406,South Africa,Africa,Southern Africa,Developing regions,3890,4200,4160,3310,2310,3310,...,9180,10590,8850,9890,7090,7900,7970,8790,13450,170800
381,Philippines,Asia,South-Eastern Asia,Developing regions,3610,4050,4430,4510,4010,4700,...,4750,4650,5290,5460,7160,8070,10040,11160,13760,186270
320,Indonesia,Asia,South-Eastern Asia,Developing regions,5990,4400,3780,4330,4070,3880,...,13640,15390,13650,13840,8970,7960,8350,8370,9960,228250
401,Singapore,Asia,South-Eastern Asia,Developing regions,2850,3560,2950,2940,2910,2920,...,12080,15390,17310,16020,16340,17520,19350,16990,18080,264300
327,Japan,Asia,Eastern Asia,Developed regions,2240,2980,2930,3200,3250,3760,...,10930,21200,24810,19030,11900,10920,10370,10640,10230,266510
319,India,Asia,Southern Asia,Developing regions,1220,1560,1870,2090,2300,2510,...,10390,9380,9240,15080,18310,19920,27880,41920,58400,291500
345,Malaysia,Asia,South-Eastern Asia,Developing regions,12390,14420,12820,12330,11690,11100,...,10900,12520,14810,16880,12540,13130,13890,13540,14950,346370
265,China,Asia,Eastern Asia,Developing regions,860,870,560,580,1220,2190,...,16700,22220,29000,33410,29860,28820,32190,42920,54300,387180
266,"China, Hong Kong Special Administrative Region",Asia,Eastern Asia,Developing regions,4170,4380,4980,5480,7450,6820,...,16410,18620,20200,19220,9740,10070,10270,9680,11030,388640
434,United States of America,Northern America,Northern America,Developed regions,10470,12080,12490,11110,11840,12480,...,18030,19230,18950,18980,18540,18490,17320,19260,20860,450370
367,New Zealand,Oceania,Australia and New Zealand,Developed regions,34370,34440,23920,13620,16900,27070,...,47230,45570,29500,28000,40710,44680,45550,39120,46960,898760
432,United Kingdom of Great Britain and Northern I...,Europe,Northern Europe,Developed regions,43540,57050,51730,31660,25150,27630,...,51000,52940,57330,70150,53140,53300,57250,61490,65160,1333340

- Check if these have all unique values or not
 - countries
 - continents (AreaName)
 - country continent pairs

In [14]:
aus_sorted.sort_values('Total',ascending=False).head(1)
aus_sorted.Country.nunique()

222

In [15]:
aus_sorted.Region.nunique()
# aus_sorted.groupby(['Country','Region']).count()

22

- Find countries for which no of immigrants for all years is 0

In [16]:
# aus_sorted.iloc[:,4:29]
aus_sorted[aus_sorted.Total!=0.0].Country.unique()

array(['Afghanistan', 'Albania', 'Algeria', 'American Samoa', 'Andorra',
       'Angola', 'Antigua and Barbuda', 'Argentina', 'Armenia', 'Aruba',
       'Australia', 'Austria', 'Azerbaijan', 'Bahamas', 'Bahrain',
       'Bangladesh', 'Barbados', 'Belarus', 'Belgium', 'Belize', 'Benin',
       'Bermuda', 'Bhutan', 'Bolivia (Plurinational State of)',
       'Bosnia and Herzegovina', 'Botswana', 'Brazil',
       'British Virgin Islands', 'Brunei Darussalam', 'Bulgaria',
       'Burkina Faso', 'Burundi', 'Cabo Verde', 'Cambodia', 'Cameroon',
       'Canada', 'Cayman Islands', 'Chad', 'Chile', 'China',
       'China, Hong Kong Special Administrative Region',
       'China, Macao Special Administrative Region',
       'China, Taiwan Province of China', 'Colombia', 'Congo',
       'Cook Islands', 'Costa Rica', "CÃ´te d'Ivoire", 'Croatia', 'Cuba',
       'Cyprus', 'Czech Republic',
       "Democratic People's Republic of Korea",
       'Democratic Republic of the Congo', 'Denmark', 'Djibouti',
       'Dominica', 'Dominican Republic', 'Ecuador', 'Egypt',
       'El Salvador', 'Equatorial Guinea', 'Eritrea', 'Estonia',
       'Ethiopia', 'Faeroe Islands', 'Falkland Islands (Malvinas)',
       'Fiji', 'Finland', 'France', 'French Guiana', 'French Polynesia',
       'Gabon', 'Gambia', 'Georgia', 'Germany', 'Ghana', 'Gibraltar',
       'Greece', 'Grenada', 'Guam', 'Guatemala', 'Guinea',
       'Guinea-Bissau', 'Guyana', 'Haiti', 'Honduras', 'Hungary',
       'Iceland', 'India', 'Indonesia', 'Iran (Islamic Republic of)',
       'Iraq', 'Ireland', 'Israel', 'Italy', 'Jamaica', 'Japan', 'Jordan',
       'Kazakhstan', 'Kenya', 'Kiribati', 'Kuwait', 'Kyrgyzstan',
       "Lao People's Democratic Republic", 'Latvia', 'Lebanon', 'Lesotho',
       'Liberia', 'Libya', 'Liechtenstein', 'Lithuania', 'Luxembourg',
       'Madagascar', 'Malawi', 'Malaysia', 'Maldives', 'Mali', 'Malta',
       'Marshall Islands', 'Martinique', 'Mauritania', 'Mauritius',
       'Mexico', 'Micronesia (Federated States of)', 'Monaco', 'Mongolia',
       'Montserrat', 'Morocco', 'Mozambique', 'Myanmar', 'Namibia',
       'Nauru', 'Nepal', 'Netherlands', 'New Caledonia', 'New Zealand',
       'Nicaragua', 'Niger', 'Nigeria', 'Niue',
       'Northern Mariana Islands', 'Norway', 'Oman', 'Pakistan', 'Palau',
       'Panama', 'Papua New Guinea', 'Paraguay', 'Peru', 'Philippines',
       'Poland', 'Portugal', 'Puerto Rico', 'Qatar', 'Republic of Korea',
       'Republic of Moldova', 'RÃ©union', 'Romania', 'Russian Federation',
       'Rwanda', 'Saint Lucia', 'Samoa', 'Saudi Arabia', 'Senegal',
       'Seychelles', 'Sierra Leone', 'Singapore', 'Slovakia', 'Slovenia',
       'Solomon Islands', 'Somalia', 'South Africa', 'Spain', 'Sri Lanka',
       'State of Palestine', 'Sudan', 'Suriname', 'Swaziland', 'Sweden',
       'Switzerland', 'Syrian Arab Republic', 'Tajikistan', 'Thailand',
       'The former Yugoslav Republic of Macedonia', 'Timor-Leste', 'Togo',
       'Tokelau', 'Tonga', 'Trinidad and Tobago', 'Tunisia', 'Turkey',
       'Turkmenistan', 'Tuvalu', 'Uganda', 'Ukraine',
       'United Arab Emirates',
       'United Kingdom of Great Britain and Northern Ireland',
       'United Republic of Tanzania', 'United States of America',
       'Uruguay', 'Uzbekistan', 'Vanuatu',
       'Venezuela (Bolivarian Republic of)', 'Viet Nam',
       'Wallis and Futuna Islands', 'Yemen', 'Zambia', 'Zimbabwe'],
      dtype=object)

- Find count of above countries

In [17]:
aus_sorted[aus_sorted.Total!=0].Country.nunique()

209

- Find countries for which no of immigrants is 0 for any year
   - DOUBT

In [79]:
# aus_sorted.iloc[:,5:29].any(axis=1)==0
# aus_sorted.shape
# aus_sorted[aus_sorted.iloc[:,5:29].any(axis=1)==0].Country.unique()
# aus_sorted[aus_sorted.iloc[:,5:29].any(axis=1)==0].shape
# aus_sorted[aus_sorted.iloc[:,5:29].all(axis=1)==0].Country.nunique()
# aus_sorted[aus_sorted.iloc[:,5:29].all(axis=1)==0].Country.shape

(21, 34)

# Save Data
- Drop the row where AreaName is 'World'

In [19]:
# Done Above

- Save the dataset to a new file AustraliaFiltered.xlsx

In [20]:
aus_sorted.to_excel(r"C:\Users\Samarpit\Desktop\LEARBAY\weekday2019_09_05\Assignments\Samarpit\AustraliaFiltered.xlsx")